### ISSUE TITLE
Use multiples api endpoints to prevent dns blocking services.

### ISSUE THREAD

**Issue by ArthurFiorette** [z0ccc/LocateJS#2]
I'm behind my homelab network with pihole, so when looking up for the `https://api.vytal.io/ip/` at https://github.com/z0ccc/LocateJS/blob/3d3325965f3be4221024d2cf0adc0feb821a3c67/src/utils/connection.js#L4-L9, the request fails with **`connection.js:5 GET https://api.vytal.io/ip/ net::ERR_CONNECTION_REFUSED`**.

I think a catch block to show a message about it or use multiples apis (or just domains) to bypass it.

_came by reddit <3_

**Comment by z0ccc** [comment]
I accidentally took down api.vytal.io when renewing the ssl certificate lol. Its back up now.
