### ISSUE TITLE
Alternate method to hide location

### ISSUE THREAD

**Issue by Theorist-Git** [z0ccc/LocateJS#5]
Hey @z0ccc , I was reading the README.md file where you mention 

> To hide your system data you will need to change your system settings. You can change your timezone to one with the same timezone offset so that the date on your computer stays the same.

But I think you can achieve that, at-least in Firefox, by going to `about:config` and setting `privacy.resistFingerprinting` to `true`, this was added to Firefox as a part of the [Tor Uplift Project](https://wiki.mozilla.org/Security/Tor_Uplift), this seems to do a good job of spoofing location/time-zone/language/user-agent etc, and I think it maybe the best solution for hiding your location while using a VPN (When your connection doesn't match your system data) other than using Tor of-course.

**Comment by z0ccc** [comment]
Good point. I plan to do a big update to the readme soon. Thanks
